<3
vegtamr-ab/computational-maths pull request #29
Opened 2020-01-19 09:47 UTC by l0gark

2020-01-19 15:00 UTC, vegtamr-ab requested changes
Убери исправление в 14й, и ок

2020-01-19 15:00 UTC, vegtamr-ab commented on src/14-rms-approximation-orthogonality.tex
> +(\ref{eq:RmsEq}) обращаются в $0$, и для $a_k$ получается готовое выражение:
Там все кроме одного, всё верно, тут не должно быть исправлений

2020-01-20 17:53 UTC, l0gark commented on src/14-rms-approximation-orthogonality.tex
> +(\ref{eq:RmsEq}) обращаются в $0$, и для $a_k$ получается готовое выражение:
там два раза написано "кроме одного"

2020-01-21 18:34 UTC, vegtamr-ab commented on src/14-rms-approximation-orthogonality.tex
> +(\ref{eq:RmsEq}) обращаются в $0$, и для $a_k$ получается готовое выражение:
справедливо

2020-01-21 18:35 UTC, merged